### ISSUE TITLE
Test, Coverage, Lint script

### ISSUE THREAD

**Issue by ryscheng** [privacylab/talek#32]
and perhaps a pre-commit hook to make sure we're doing it
And some CI too

**Comment by ryscheng** [comment]
maybe we can just use this one
https://github.com/keybase/kbfs#code-style

**Comment by willscott** [comment]
the kbfs code style looks good.

**Comment by willscott** [comment]
we are currently in a state where go fmt / go vet / go test pass everywhere.
There aren't precommit hooks yet, which maybe is worth adding, but code style is up-to-par.
I've been using gometalint which has a few additional naming things i've tried to comply with as well.

**Comment by ryscheng** [comment]
Added testing and linting in https://github.com/privacylab/talek/pull/52

**Comment by ryscheng** [comment]
Added coverage reporting in https://github.com/privacylab/talek/pull/54
