### ISSUE TITLE
Consistency and Safety of Write Epoch application

### ISSUE THREAD

**Issue by willscott** [privacylab/talek#42]
The initial implementation of this functionality in #39 uses a `NextEpoch` call in the follower API,  but because this goes along a separate channel within the Shard, it may be inconsistent in when it is applied in different replicas.

Probably, adding a field to WriteArgs (or different structs passed between servers versus the client-server interface, preferably) is going to be an easier long-term way to do this, but required a it more refactoring than this initial implementation.

**Comment by ryscheng** [comment]
Current NextEpoch call will most certainly introduce inconsistencies. 

The current proposal is to add a field into WriteArgs such that when the Writes are serialized, we know exactly when to flip to the next Epoch

**Comment by willscott** [comment]
epochs are folded back into the serialized write pipeline in #51

**Comment by willscott** [comment]
closing as obsolete
