### ISSUE TITLE
Bloom should be in vendor?

### ISSUE THREAD

**Issue by willscott** [privacylab/talek#53]
it looks like the `bloom/` directory is 3rd party code. why isn't it in vendor?

**Comment by ryscheng** [comment]
I vaguely recall needing to make changes. Let me double check

**Comment by willscott** [comment]
If it's modified, i feel like the correct setup would be:
* forked repo in privacylab org with changes
* that repo referenced, and then in vendor

**Comment by ryscheng** [comment]
👍

**Comment by ryscheng** [comment]
https://github.com/privacylab/talek/pull/59
